<a href="https://colab.research.google.com/github/Amanbhalerao/Data_science_Lab_SE_05/blob/main/practicl_No_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 1. Create a sample square matrix
# Let's define a 3x3 matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("Original Matrix A:")
print(A)

Original Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
# 2. Calculate the determinant of the matrix
determinant_A = np.linalg.det(A)
print(f"\nDeterminant of A: {determinant_A}")


Determinant of A: 0.0


In [3]:
# Check if the determinant is non-zero to ensure invertibility
if abs(determinant_A) > 1e-9: # Using a small tolerance for floating point comparison
    # 3. Find the inverse of the matrix
    A_inv = np.linalg.inv(A)
    print("\nInverse of Matrix A:")
    print(A_inv)

    # Verify the inverse (A * A_inv should be close to identity matrix)
    identity_check = np.dot(A, A_inv)
    print("\nVerification (A * A_inv):\n", identity_check)
else:
    print("\nMatrix A is singular (determinant is zero or close to zero), so its inverse does not exist.")


Matrix A is singular (determinant is zero or close to zero), so its inverse does not exist.


In [4]:
# 4. Solve a system of linear equations (AX = B)
# Let's define a new invertible matrix A and vector B
A_solve = np.array([[3, 1],
                    [1, 2]])
B_solve = np.array([9, 8])

print("\nSystem of Linear Equations: AX = B")
print("Matrix A:")
print(A_solve)
print("Vector B:")
print(B_solve)

# Solve for X
X = np.linalg.solve(A_solve, B_solve)

print("\nSolution X:")
print(X)

# Verify the solution
print("\nVerification (A * X):")
print(np.dot(A_solve, X))


System of Linear Equations: AX = B
Matrix A:
[[3 1]
 [1 2]]
Vector B:
[9 8]

Solution X:
[2. 3.]

Verification (A * X):
[9. 8.]
