<a href="https://colab.research.google.com/github/Amanbhalerao/Data_science_Lab_SE_05/blob/main/practical_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

# Define the coefficient matrix A
A = np.array([[2, 3],
              [4, 5]])

# Define the constant vector B
B = np.array([10, 20])

# Solve the system of linear equations
solution = np.linalg.solve(A, B)

print("Solution to the system of equations:")
print(f"x = {solution[0]:.2f}")
print(f"y = {solution[1]:.2f}")

Solution to the system of equations:
x = 5.00
y = 0.00


In [4]:
# Compute the inverse of the matrix
try:
    inverse_matrix = np.linalg.inv(matrix)
    print("\nInverse of the matrix:")
    print(inverse_matrix)
except np.linalg.LinAlgError as e:
    print(f"\nError: {e}. The matrix might be singular (non-invertible).")


Inverse of the matrix:
[[ 0.10638298 -0.15957447  0.22340426]
 [ 0.09574468  0.10638298 -0.14893617]
 [-0.19148936  0.28723404 -0.20212766]]


In [1]:
import numpy as np

In [2]:
# Create a 3x3 square matrix with random integer values
matrix = np.random.randint(0, 10, size=(3, 3))

print("Original 3x3 matrix:")
print(matrix)

Original 3x3 matrix:
[[4 6 0]
 [9 4 7]
 [9 0 5]]


In [3]:
# Compute the determinant of the matrix
determinant = np.linalg.det(matrix)

print(f"\nDeterminant of the matrix: {determinant}")


Determinant of the matrix: 187.99999999999983
